### ISSUE TITLE
Build failure

### ISSUE THREAD

**Issue by krefson** [CDrummond/melodeon#14]
I am attempting to build on OpenSuSE Leap 15.6 with Qt6 version 6.6.3. The cmake configuration works, but compile fails with:

````/home/kr/build/melodeon/src/mainwindow.cpp: In member function ‘QString MainWindow::buildUrl()’:
/home/kr/build/melodeon/src/mainwindow.cpp:414:27: error: ‘class QProcess’ has no member named ‘startCommand’; did you mean ‘splitCommand’?
                 gsettings.startCommand(QLatin1String("gsettings get org.gnome.desktop.wm.preferences button-layout"));
                           ^~~~~~~~~~~~
                           splitCommand

````

any suggestions?

Keith

**Comment by CDrummond** [comment]
Looks like your build is picking up Qt5 headers - as `startCommand` has been part of `QProcess` since 6.0 - see https://doc.qt.io/qt-6/qprocess.html#startCommand

**Comment by krefson** [comment]
Indeed "cmake" was picking up Qt5 not Qt6. I might humbly suggest that the CMakefile.txt check Qt version dependencies, which would have revealed this a little more obviously.  In any case, now up and running after a little cmake twiddling, so thank you.
